{{- if and (.Values.forecastle).enabled (.Capabilities.APIVersions.Has "forecastle.stakater.com/v1alpha1") (or .Values.ingress.enabled .Values.route.enabled) }}
apiVersion: forecastle.stakater.com/v1alpha1
kind: ForecastleApp
metadata:
  name: {{ template "application.fullname" . }}
  namespace: {{ include "application.namespace" . }}
  labels:
  {{- include "application.labels" . | nindent 4 }}
{{- if .Values.forecastle.additionalLabels }}
{{ toYaml .Values.forecastle.additionalLabels | indent 4 }}
{{- end }}
spec:
  name: {{ .Values.forecastle.displayName }}
  group: {{ default .Release.Namespace .Values.forecastle.group }}
  icon: {{ .Values.forecastle.icon }}
  urlFrom:
  {{- if .Values.ingress.enabled }}
    ingressRef:
      name: {{ template "application.fullname" . }}
  {{- else }}
    routeRef:
      name: {{ template "application.fullname" . }}
  {{- end }}
  networkRestricted: {{ .Values.forecastle.networkRestricted }}
  {{- if .Values.forecastle.properties }}
  properties:
{{ toYaml .Values.forecastle.properties | indent 4 }}
  {{- end }}
{{- end -}}